name: layout.hsty.vn

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - name: ðŸ“¥ Checkout code
      uses: actions/checkout@v3
      
    - name: ðŸš€ Deploy to Hostinger via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: 156.67.222.66
        username: ${{ secrets.FTP_USERNAME_HSTY_Layout }}
        password: ${{ secrets.FTP_PASSWORD_HSTY_Layout }}
        server-dir: /public_html/
        local-dir: ./
        exclude: |
          .github/**
          .git/**
          .*
          vite.config.js
          README.md
          phpunit.xml
          package.json
          package-lock.json
          vendor/**
          resources/css/**
          resources/js/**
          backups/**
          htmldraft/**
          tests/**
          websocket-server/**
